name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci
      - name: Build
        run: npm run doc:build

      - name: Move built files to root directory and clean up
        run: |
          rm -rf guide reference
          mv doc/.vitepress/dist/* ./
          rm -rf doc/.vitepress/dist

      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: doc/.vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
